### ISSUE TITLE
A complete beginner's guide to dosemu2

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1145]
A few posts here have asked for help in setting up dosemu2. Here is a guide for complete beginners, suitable for people who have never used Linux, but recently installed Ubuntu and want to run DOS applications. Any experienced Linux user will NOT need most of these instructions, but complete beginners may find them useful.

This procedure has been tested on Ubuntu 20.04, and applies ONLY to Ubuntu 20.04.

1. Click on Activities, search for Terminal; when the Terminal icon appears, right-click on it and select Add to Favorites from the pop-up menu.

2. Click on the Terminal icon in the sidebar and enter these commands, responding to any prompts as they appear (you will need to enter your password):

`sudo add-apt-repository ppa:dosemu2/ppa`
`sudo apt update`
`sudo apt install dosemu2`

3. Exit the Terminal.

4.  Click on Activities again, search for dosemu; when the DOS emulator icon appears, right-click on it and select Add to Favorites from the pop-up menu.

5. Click once on the dosemu2 icon on the sidebar; dosemu2 will open; enter the command "exitemu" (no quotation marks) to close it.

6. Open the file manager from the file-folder icon in the sidebar. Click on the options menu on the toolbar (the "hamburger" or three-line icon), and select Show Hidden Files.

7. In the file manager sidebar, navigate to your Home folder and, in the list of folders inside the Home folder, click on .dosemu (note the initial dot) to open it. The folder named drive_c is the C: drive in dosemu2. You can copy files or folders in that folder (perhaps dragging them from your Downloads folder or anywhere else).

8. (OPTIONAL) If you want to have more than one available drive in your system (for example, drives D: and E:), then click on the options button again, and then click on the "new folder" icon at the upper right of the menu; enter the name "drives" (no quotation marks) to create a folder named drives at the same level as the folder named drive_c. Click on the drives folder to open it;  when you are in the empty drives folder, click on the options button again, click on the "new folder" icon and create a folder named "drive_d"; repeat with "drive_e" if you want a drive E:

9. Close the file manager and open the Terminal again. Enter these commands:

`cd ~/`
`cp -i /etc/dosemu/dosemu.conf ~/`
`mv -i dosemu.conf .dosemurc`

(Notice the dot in the third line.) This will made a user-editable copy of the dosemu2 configuration file. 

10. (OPTIONAL.) Still in the terminal, enter (and keeping in mind the dot in the filename):

`gedit ~/.dosemurc`

If you plan to run WordPerfect for DOS 6.x find the line that reads

`# $_cpu_emu = “off” `

and change it by removing the comment (#) at the start and changing the rest of the line to read

`$_cpu_emu = “vm86sim”`

If you created additional drive letters in step 8, then find the line that reads

`# $_hdimage = "+0 +1"`

and change it by removing the comment (#) at the start and changing the rest of the line to read

`$_hdimage = "+0 drives/* -18 +1"`

If you created two additional drives in step 8, this will cause them to be mounted as drives D: and E:, and will mount the three drives used internally by dosemu2 as drives X:, Y:, and Z:. Save and close the file.

11. (OPTIONAL). To install a printer, click Activities, search for Printers, and select Printers. When the Printers window opens, click Add a Printer. When CUPS-BRF-Printer appears, ignore it, and enter the address of a network in the field at the bottom of the dialog box (for example, http://192.168.1.99). Your printer may appear with two or more different names; choose the friendliest name and click Add.

When the printer appears in the printer list, click on the gear icon and add a checkmark next to Use Printer by Default. You may want to look other options on this menu. When you are done, close the Printers window.

12. (OPTIONAL.) If you don't like the default dosemu icon, download this file to your Downloads folder:

[](http://www.columbia.edu/~em36/wpdos/dosemu.xpm)

Then, open the terminal and enter this command:

`sudo cp -i ~/Downloads/dosemu.xpm /usr/share/dosemu/icons`

You will need to log out and in again to see the new icon.

13. (OPTIONAL.) To create a user-level autoxec.bat start dosemu2 and create a file named C:\USERHOOK.BAT and enter commands into it. You can do this at the dosemu2 prompt by entering commands like this

`echo CD WP51>C:\USERHOOK.BAT`
`echo WP>>C:\USERHOOK.BAT`

Notice the two greater-than signs in the second line. When you restart dosemu, these commands will run automatically.

14. (NOTE.) The autoexec.bat used by default for dosemu is /usr/share/dosemu/dosemu2-cmds-0.2/fdppauto.bat . You can edit it by opening it with "sudo gedit [filename]" in the terminal but you shouldn't need to.

**Comment by stsp** [comment]
This is an interesting guide indeed,
thanks! There are some small mistakes,
for example you never need to uncomment
the config line without changing it, as
the commented out lines represent
their default value.
But as it is specific to ubuntu, I think
this is a wiki material. So would you
like adding it to wiki?
We can then reference it in readme.

**Comment by stsp** [comment]
If you want dosemu to run the
command and exit, you need to
pass that command to -E or -K
but not alter autoexec.

**Comment by emendelson** [comment]
Thank you. I've fixed the mistakes, and will of course add this to the wiki. I'm hoping to update this ten-year-old page also:

http://wpdos.org/linux.html

and will have a question or two in a different thread.

**Comment by emendelson** [comment]
I've added the page to the wiki. I'll be glad to have any mistakes fixed.

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/wiki/Setup-guide-for-complete-beginners-(using-Ubuntu)

```
If you plan to run WordPerfect for DOS 6.x find the line that reads

# $_cpu_emu = “off”

and change it by removing the comment (#) at the start and changing the rest of the line to read

$_cpu_emu = “vm86sim”
```

Why do you need that?
Have you filled a bug, if there is one?

**Comment by stsp** [comment]
Maybe you can also return the
examples of running WP, but with
-E and/or -K.

**Comment by emendelson** [comment]
Will file a bug about WPDOS 6.x. About using -E and/or -K, I will have to figure out how to create or modify a launcher in current Ubuntu. Until yesterday, I hadn't looked at Ubuntu since around 2014, so I remember almost nothing, and everything I remember is out of date.

**Comment by emendelson** [comment]
I'm completely confused by -E and/or -K. I think I can figure out that the command "system -e" has to be the end of an autoexec.bat, but I've tried adding it to fdppauto.bat and to userhook.bat, and then running dosemu from a launcher with an exec like this:

`Exec=/usr/bin/dosemu -E wp51\wp.com`

but the command doesn't run. I think, from old DOSEMU, that -E causes the emulator to stay open after running the command, but I can't figure out what -K does. 

Can anyone provide step-by-step instructions for using -E or -K?

**Comment by stsp** [comment]
Try from terminal first.
dosemu -E mem -td
dosemu -K ./wp.com

**Comment by emendelson** [comment]
The default configuration doesn't include mem, so the first of those commands doesn't do anything.

I've put mode.com in the root directory, and this command:

dosemu -E mode

produces the output of mode.com, and then the emulator immediately closes.

But this command

dosemu -K ./mode.com 

simply opens the emulator to the DOS prompt.

**Comment by stsp** [comment]
You can use -T to avoid close.
-K expects linux path.

**Comment by emendelson** [comment]
I've added instructions for installing kvm, and I hope they're accurate. I'll check this again on a clean system in a few days.

**Comment by emendelson** [comment]
OK, I finally stopped being completely stupid, and figured out the switches:

-E requires escaped backslashes if I use a DOS path:

`dosemu -E c:\\wp51\\wp.com -T`

and -K is (like everything else in Linux, if I had the brains to remember this) case-sensitive:

`dosemu -K ~/.dosemu/drive_c/WP51/WP.COM -T`

**Comment by emendelson** [comment]
And, in a desktop launcher file, -E requires double-escaped backslashes, like this:

`Exec=/usr/bin/dosemu -E c:\\\wp51\\\wp.com`

**Comment by stsp** [comment]
Try avoiding tilde.

**Comment by emendelson** [comment]
> 
> 
> Try avoiding tilde.

Yes. Another thing I should have figured out for myself. Thank you.

And $HOME also works in place of the tilde.

**Comment by kmm2** [comment]
Thank you for the guide. Where do I change "files=255"?
There is no config.sys in in drive_c (dosemu v1) and 3 configs in /usr/share/dosemu/dosemu2-cmds-0.2/
**config.sys 
fdconfig.sys 
fdppconf.sys**
Which one is active by default?
fdppconf.sys seems active but files=255 makes no difference there.

**Comment by stsp** [comment]
Obviously it depends on what DOS
do you run. Every config.sys is for
different DOS, which is said in the
comment in the first line of the config.

@emendelson would you like to mention
userhook.sys in your guide? It seems
to only mention userhook.bat.

**Comment by emendelson** [comment]
@stsp - Yes, I will add this. I didn't know about userhook.sys until now.

**Comment by stsp** [comment]
I wouldn't say it is processed _after_.
It is more like _before_ or even together.
config.sys does not have a strict ordering,
as has autoexec. It chooses the sequence
of operations by their priorities, rather then
by how they are written.
Also it would be good to mention that
userhook.sys/bat are only used with fdpp,
and that userhook.sys is good for things
like `files=255` and alike.

**Comment by kmm2** [comment]
Can you please explain more about "Every config.sys is for different DOS"?
Is fdppconf hard-coded or preset in a variable to be the DOS in this selection:
```
/usr/share/dosemu/dosemu2-cmds-0.2/
config.sys
fdconfig.sys
fdppconf.sys
```
Anyway, as FreeDOS has not worked for my app (it worked in dosemu v1), I copied MSDOS6 to .dosemu/drive_c and it is all good there. Is there a better location for a different DOS?

Next question, so dosemu checks 'C' for DOS files and prioritizes them over the pre-installed FreeDOS, right? What OS file specifically it is looking for to make such s switch?

**Comment by stsp** [comment]
> Can you please explain more about "Every config.sys is for different DOS"?

Just look at the first line of every config.
It says what DOS it configures.

> Is fdppconf hard-coded or preset in a variable to be the DOS in this selection:

I don't understand this question.
Nothing is hardcoded, and fdppconf.sys
is not the only possible config, but it is
supposed to be used in a default install.
And it is not supposed to be changed, as
any other configs in the location you found.

> Anyway, as FreeDOS has not worked for my app (it worked in dosemu v1)

Freedos support is coming to an end, yes.
But there are light years between me and
an understanding of your problem.
It will really help if, instead of asking questions,
you will just explain your problem.

> Next question, so dosemu checks 'C' for DOS files and prioritizes
> them over the pre-installed FreeDOS

There is no pre-installed freedos, as it was in dosemu1.
If you built from sources with dosemu-freedos
package, then you get the config that we barely
support, and may only fix its problems if they are
important and clearly explained. When doing
custom configs, you must be very well aware
of what you do, and its not the case here.
But indeed, the OS in drive C takes a priority -
that makes dosemu2 very costomizable, and
confuses all new users unfortunately, so I wonder
if such customization should be removed.

> What OS file specifically it is looking for to make such a switch?

dosemu2 is very customizable.
It can find different command.com on
C, or different config.sys, or different
kernel - whatever it finds on C, it takes
as a sign that user wanted a customization
of any part of the boot process.
Being a great feature in theory, perhaps
that should be removed.

**Comment by kmm2** [comment]
> It will really help if, instead of asking questions, you will just explain your problem.

Sure, here is the original problem with fdpp:

- dosemu2/bionic,now 2.0~ pre8-6123-51906bf+202005220032~ubuntu18.04.1 amd64
- userhook.sys contains files=255
- DOS app crashes - [crash-boot.log](https://github.com/dosemu2/dosemu2/files/4692489/crash-boot.log) 

```
 OPENING FILES...PLEASE WAIT
 ERROR: fdpp: abort at /build/fdpp-M8bIGp/fdpp-1.0~rc2
 fdpp crashed.ptr.hpp:604
```
After reading the old 1.4 doc, I copied MSDOS6 to drive_c and it works now, CONFIG.SYS is standard:
```
device=himem.sys
dos=high,umb
files=255
buffers=30
stacks=9,256
lastdrive=z
```
Should you decide to remove support for DOS in C, please describe the steps needed to replace FDPP with MSDOS.

**Comment by stsp** [comment]
Could you please install the dbgsym
packages for fdpp and recreate the log?

**Comment by kmm2** [comment]
I can't find fdpp-dbgsym:
```
apt-get install fdpp-dbgsym=1.0~rc2-998-2d38039+202005202301~ubuntu18.04.1
E: Unable to locate package fdpp-dbgsym
```
Would dosemu use such fdpp dbgsym automatically after installation, or something more needs to be done?

The DOS database app opens up around 200 files. Without userhook.sys files=255 the app just stops with a typical quit error message and fdpp does not crash at all. With files=255 fdpp crashes and it seems like it simply runs out of memory for so many files. I hope it helps, thanks in advance.

**Comment by stsp** [comment]
[fdpp_1.0~rc2-1_amd64.deb.gz](https://github.com/dosemu2/dosemu2/files/4696626/fdpp_1.0.rc2-1_amd64.deb.gz)
[fdpp-dbgsym_1.0~rc2-1_amd64.ddeb.gz](https://github.com/dosemu2/dosemu2/files/4696630/fdpp-dbgsym_1.0.rc2-1_amd64.ddeb.gz)

Here we go, I built the package and
dbgsym for you.

**Comment by kmm2** [comment]
Thank you, I removed the original fdpp and tried to install fdpp_1.0~rc2-1_amd64 and get:
```
The following packages have unmet dependencies:
 fdpp : Depends: libgcc-s1 (>= 3.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
On my OS I see only:
```
libgcc-7-dev/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed]
libgcc1/bionic-updates,bionic-security,now 1:8.4.0-1ubuntu1~18.04 amd64 [installed]
```
Can you compile the lib statically?

**Comment by stsp** [comment]
OK, all dbgsym packages are now available at PPA.

**Comment by kmm2** [comment]
```
apt install fdpp-dbgsym=1.0~rc2-998-2d38039+202005202301~ubuntu18.04.1
E: Unable to locate package fdpp-dbgsym
apt install fdpp-dbgsym
E: Unable to locate package fdpp-dbgsym
apt install dosemu2-dbgsym
E: Unable to locate package dosemu2-dbgsym
```
How can I install it?

**Comment by kmm2** [comment]
I downloaded it and directly installed the ddeb...
```
fdpp/bionic,now 1.0~rc2-999-bb2bc71+202005282327~ubuntu18.04.1 amd64 [installed,automatic]
fdpp-dbgsym/now 1.0~rc2-999-bb2bc71+202005282327~ubuntu18.04.1 amd64 [installed,local]
```
New log seems unchanged - [boot2.log](https://github.com/dosemu2/dosemu2/files/4699468/boot2.log) - "No symbol table info available"

How to run fdpp-dbgsym?

**Comment by stsp** [comment]
You may want to install dbgsym also
for dosemu2 to avoid that message.
But the log is much better already now,
so I will take a look.

**Comment by stsp** [comment]
I think you need `sudo apt-get update`
before you can install the symbols
with aptget.

**Comment by stsp** [comment]
I updated packages on LP, please try again.

**Comment by kmm2** [comment]
Awesome, it works now. Thank you!
I'll gladly get rid of MS-DOS and use only open-source.
I note that #define SFTMAX 128 was increased to 256, so the problem was a self-limit of the number of open files.

Incidentally, in SDL and X mode it is impossible to make block/rectangle selection for clipboard copy. Can it be fixed?

Thank you again.

**Comment by stsp** [comment]
> Awesome, it works now. Thank you!

For the future: please open new tickets,
don't re-use the existing ones.

> I note that #define SFTMAX 128 was increased to 256, so the problem was
> a self-limit of the number of open files.

At least I think so. :)
Bart, is it correct that SFTMAX defines the
number of open files? Can there be some
pitfalls with JFT or whatever else?

> Can it be fixed?

Its not a bug: any text selection behaves
that way. Just select this particular text that
you read now.
If you have some proposal, please open
another ticket.

**Comment by ecm-pushbx** [comment]
I haven't looked into it but SFTMAX should probably be 255 at most. The value 0FFh (256th value) indicates a closed handle in the Process Handle Table (JFT).

**Comment by stsp** [comment]
But this doesn't seem to be the case
with SFT. If I read the code correctly,
close only decrements sft_count.
Also it seems perfectly legal to have
FILES=255

**Comment by ecm-pushbx** [comment]
FILES=255 yes. FILES=256 no.

**Comment by stsp** [comment]
But I think SFTMAX=FILES+1.
But I am not sure.
For example I see SFTMAX being compared
to the file name length! :(

**Comment by emendelson** [comment]
And now that all the essential fixes have been made to dosemu2 and xsel, I've updated my WordPerfect-under-Linux page. Some of the information may be useful to beginners, but all the essentials are in the wiki here:

http://wpdos.org/linux.html

**Comment by stsp** [comment]
```
cd ~/
cp -i /etc/dosemu/dosemu.conf ~/
mv -i dosemu.conf .dosemurc
gedit ~/.dosemurc
```

This is a deprecated location that may
be removed. Please recommend ~/.dosemu/.dosemurc

**Comment by stsp** [comment]
Also its not necessary to do the config copy.
It is much easier to just write down 1-2 lines
that you want to get modified.

**Comment by stsp** [comment]
`$_hdimage = "+0 /home/YOURUSERNAME/ +1"`

This is an unsafe, unrecommended setup.
Why not ` /home/YOURUSERNAME/wp6` or alike?

**Comment by emendelson** [comment]
Will fix all these things - probably tomorrow. Will suggest something like /home/YOURUSERNAME/DosData

**Comment by emendelson** [comment]
Have also revised the wiki with the recommended location of .dosemurc

**Comment by emendelson** [comment]
Have revised my page to match these corrections. I've also rewritten my WPDOS macros so they don't require accessing anything in the home folder.

**Comment by stsp** [comment]
Just the fact that documentation is outdated.
Would you like to create the PR fixing that?

**Comment by emendelson** [comment]
> Just the fact that documentation is outdated.
> Would you like to create the PR fixing that?

Done.

**Comment by npmcs** [comment]
It might be worth adding some help on using the lredir command to map drive letters to other locations 
for example
LREDIR F: linux\fs/path to directory
This can also be added to the autoexec.bat file

**Comment by npmcs** [comment]
I am not sure the space was clear in the above example after the F: 
LREDIR F:  linux\fs/path to directory

**Comment by emendelson** [comment]
The LREDIR command is already in there; search for it. 

And while I'm here, is there anything in the wiki that's now outdated?

**Comment by stsp** [comment]
Many things have outdated on your wp
page, but as for wiki - its not the best time
to update it right now, as I am in a process
of some big changes. lredir will most likely
change.

**Comment by emendelson** [comment]
OK, will wait and ask you about updates to my page and the wiki when things are more stable. I think I saw that separate installation of kvm may not be necessary, but I'll ask to sort that out later.

**Comment by stsp** [comment]
kvm not necessary - is just one of
many problems disappeared.
I think no problems that you mentioned,
are still valid.

**Comment by emendelson** [comment]
OK - I got rid of the kvm stuff in the wiki, and will fix my web page. I don't see anything else in the wiki that needs to be changed, but maybe I'm not looking closely enough.

**Comment by stsp** [comment]
I was talking about your wp page.
You no longer need to install kvm to
run wp, among other things.

**Comment by stsp** [comment]
lredir changes have occurred.
Would be nice if some review is
done from the user's perspective,
and the doc is written about lredir/lredir2.
I hate the lredir2 name, as it is now
doing the entirely different things...
Maybe while documenting, there would
be some ideas about what functionality
to add and what name to change.

**Comment by emendelson** [comment]
I've been distracted, but will get to this in the next few days. Is there any information available that I can use when trying to document lredir2?

**Comment by stsp** [comment]
Of course, both lredir and lredir2 have
a help screen displayed with -h switch.

**Comment by emendelson** [comment]
I started to write about lredir and lredir2 but couldn't figure out what changed in lredir from what I wrote in the wiki. Can you give any guidance.

About lredir2 - I *think* I see that it handles redirection of already existing dosemu paths. Maybe call it dosredir instead of lredir2? The "L" in lredir seems to stand for Linux, so "dosredir" might be a clearer name?

**Comment by stsp** [comment]
Just a few notes:
- \\LINUX\FS prefix is not necessary these days
- you can also use `dosemu -d /tmp/my_drive_to_map`
instead of lredir - this has an advantage of not having
to edit any config (but the disadvantage that its not
permanent)

`dosredir` is probably a too long name, at least to
my taste. How about `mdrive` or `mdrv` aka "manage
drives"?
Anyway, whoever has an opinion on how lredir2
should actually be called - its time to spell your ideas.
Initially I thought the original lredir would be retained
for compatibility only, and deprecated, so lredir2 with
new syntax - made sense. But now, lredir also has a
new syntax, and is not dying at all, and lredir2 went a
completely different route. So time for some rename.

**Comment by emendelson** [comment]
As a name, how about `dsubst`?  lredir2 is a lot like DOS subst...

**Comment by stsp** [comment]
A possible candidate indeed.
However keep in mind that it can
also emulate cdrom, otherwise we
could probably just use DOSish subst.

**Comment by emendelson** [comment]
Also, `dosemu -d` needs to be added to the help screen.

**Comment by stsp** [comment]
Done.

**Comment by stsp** [comment]
Note that lredir2 can delete and _restore_
the redirections previously done with lredir
or -d or whatever else.
So its still a bit more than just subst.

**Comment by stsp** [comment]
(no, it doesn't seem capable of restoring
the deleted redirections of lredir. But it can
restore deleted -d and fatfs redirections)

**Comment by stsp** [comment]
So another candidates:
redirman, fstool, retool. :)

**Comment by emendelson** [comment]
`dirutil` ??
`dskutil` ??

**Comment by stsp** [comment]
drvutil perhaps, as dskutil suggests
some business with disk (like partitioning),
and dirutil doesn't apply well (it manipulates
drives, not directories)

**Comment by stsp** [comment]
If someone finds any of the above
proposals cool, please vote. :)

**Comment by andrewbird** [comment]
Driveman?

**Comment by emendelson** [comment]
`drvutil` sounds best to me...

**Comment by stsp** [comment]
Yep, driveman or redirman sound
stylish; drvutil is good too. :)

**Comment by stsp** [comment]
`emudrv`?
The biggest advantage is that
we already have emuXX tools.

**Comment by andrewbird** [comment]
emudrv is fine by me.

**Comment by emendelson** [comment]
`emudrv` is fine. It says that the program emulates a drive, which is basically what it does.

**Comment by stsp** [comment]
Done in #1267

**Comment by stsp** [comment]
... and merged.
@emendelson anything else I can
do before documenting?

**Comment by emendelson** [comment]
@stsp - I just ran sudo apt upgrade, and dosemu2 still has an lredir2 command, not an emudrv command. Am I missing something??

**Comment by stsp** [comment]
It is daily built. so coming soon.

**Comment by emendelson** [comment]
Documented. There's a misspelling in the emudrv help screen: "host paths", not "host pathes".

**Comment by stsp** [comment]
```
cd ~/.dosemu
cp -i /etc/dosemu/dosemu.conf ~/.dosemu
mv -i dosemu.conf .dosemurc
```

Can be replaced with just:
```
cp /etc/dosemu/dosemu.conf ~/.dosemu/.dosemurc
```
But I wouldn't recommend that.
Having a messy ~30K local config
is not helpful at all. The user should
only have 1-2 lines there, which he
can either understand or copy/paste
here to ask for a help.

`"-nn" number tells dosemu2 how many drive letters to skip before creating its internal drive letters.)`

... "before creating the subsequent drives".

`(where you can set (for example) files=255`

Missing right-bracket.

> You can create and add to the file from the dosemu2 prompt by entering commands like this

Sigh, normally you would do `copy con file_name`
to create the file and type in the text interactively.
But this is still broken in comcom32.

> usr/share/dosemu/dosemu2-cmds-0.2/fdppconf.sys

usr/share/dosemu/commands/fdppconf.sys

> emudrv command alone, without parameters, lists existing drive assignments

Actually no, it shows help.
lredir2 did what you say.

> and for 25-line mode mono, enter:

IIRC you wanted to add some custom mono modes.

> Many of these procedures are optional;

Please emphasize that dosemu2 is supposed
to work out-of-the-box, so for just starting it and
running some program or a game, this all is
_not needed at all_ (rather than optional).
So I won't even call it a beginner's guide - its
rather an advanced usage guide. :)
Beginners should just start it, w/o reading
anything at all, and we need to hint them
so, before they got scared. :)

**Comment by andrewbird** [comment]
> There's a misspelling in the emudrv help screen: "host paths", not "host pathes".

Actually there were two in emudrv, one remains.
~~~
$ git grep pathes src
src/dosext/builtins/lredir.c:   printf("use of host pathes is deprecated in emudrv, use lredir\n");
~~~

Since host paths are now unsupported on emudrv, it should probably say that, not deprecated.

One further thing. Since there's a `-w` option to display the unix path, I think it's cleaner not to display it along with the drives when using the `-s` option, what do you think?

**Comment by stsp** [comment]
Done.

**Comment by andrewbird** [comment]
Thanks!

**Comment by emendelson** [comment]
Fixed the wiki as suggested. I wrote that you don't recommend copying the full conf file, but that I find it easier to work with it. Feel free to change anything I wrote - it's your program!!!

> IIRC you wanted to add some custom mono modes.

That's right, but they never got added, because no one could figure out how exactly how mode 7 worked. It seemed very complicated when we talked about it a few months ago. (I'll try to find the thread.)

**Comment by stsp** [comment]
For the record, you moved the document here:
https://github.com/dosemu2/dosemu2/wiki/Setup-guide-for-advanced-users-and-ambitious-beginners-(using-Ubuntu)

> A few posts here have asked for help in setting up dosemu2.

Mainly those who already have dosemu1
setup. :) Which is an entirely different matter.
But whatever.

> That's right, but they never got added, because no one could figure out how exactly how mode 7 worked.

It was a year ago.
Please don't re-hash the old threads
w/o making sure the problem is still there.
Review your WP guide, its full of old
problems like that one.

**Comment by emendelson** [comment]
As far as I can tell, there's still no way to make a custom (35-line, 43-line, etc.) mono mode.

**Comment by stsp** [comment]
Add it.

**Comment by emendelson** [comment]
That's exactly what I tried to do here:

https://github.com/dosemu2/dosemu2/issues/1156#issuecomment-631523716

Are you saying that this should work now?

**Comment by stsp** [comment]
Why not to try?

**Comment by emendelson** [comment]
I did try! And this works! Thank you!

`{0x31, -1, TEXT, TEXT_MONO, 4, 720, 560, 80, 35, 9, 16}, /* 49 */`

One problem: the underline attribute isn't supported. You can get an underline in 25-line mode 7, but in this 35-line mode.

Also, a question: When I use WPDOS's graphic preview, and then return to text mode, the text mode screen returns to 25-line mono mode. Can there be a way to force dosemu2 to remember the previous text mode after returning from a graphic mode?

**Comment by stsp** [comment]
Applied a few (mostly untested) fixes.

**Comment by emendelson** [comment]
Underline now works; thank you. 

Dosemu2 still forgets the earlier text mode when switching to and from graphics mode. Maybe there could be a command-line switch that sets the default text mode?

**Comment by stsp** [comment]
I don't think any "default mode" is possible,
but with xmode you might be able to set any
mode you want from within wp?
Does it work better on other emulators?

**Comment by emendelson** [comment]
vDos lets you set a text screen size in its config.txt file, and it remembers that size when switching in and out of graphics mode. DOSBox-X doesn't do that, but I've built by own DOSBox-X that has a hacked 43-line mode 3, and it remembers that.

It's not practical to me to keep building dosemu2 with a hacked mode 3, but it would be good if dosemu2 could have something like the vDos method of setting a screen size before startup. 

Also, sorry for thread drift, but could dosemu.conf list the available options for X_font?

**Comment by stsp** [comment]
> vDos lets you set a text screen size in its config.txt file

This is likely similar to just hack the mode
7 instead of adding a new one.

> like the vDos method of setting a screen size before startup.

For every mode?
Well, maybe xmode.com can be extended
to allow to "hack" any mode before setting
it...
But for now, please just call xmode.com
explicitly from within wp to force any mode
you need.

> Also, sorry for thread drift, but could dosemu.conf list the available options for X_font?

Added, but I think we need to switch
to the unicode font instead.
Bart, I can vaguely remember you played
around some univga font. What was the
outcome?

**Comment by emendelson** [comment]
Agreed: a unicode font would be best.

About setting screen size: vDos has separate settings for screen size and text colors. So you can set the screen size to 135 cols by 60 rows (or whatever) and set colors to vga or mono. 

About the underline mode in >25 lines: this isn't only for WordPerfect, but also for XyWrite and anything else that lets you use >25-line text modes. (I think WordStar too.)

**Comment by stsp** [comment]
> About setting screen size: vDos has separate settings for screen size and text colors.

It probably allows you to hack the
default mode 3. Maybe we can do
that too with xmode, open feature
request. So far I am sure you have
a work-around.

> About the underline mode in >25 lines: this isn't only for WordPerfect

But I am sure on other emulators
you will not succeed in adding a
custom mono modes. Its just that
you can hack on mode 7 there.

**Comment by emendelson** [comment]
> But I am sure on other emulators
you will not succeed in adding a
custom mono modes. Its just that
you can hack on mode 7 there.

For DOSBox (and now for DOSBox-X) I created 35-line, 43-line, 50-line, 132x35, and other modes. All I have to do is enter MODE MONO after switching to one of those modes, and mono mode works, with the underline:

[https://imgur.com/a/SJsodqD](url)

**Comment by stsp** [comment]
How have you created them, and
with what numbers?
Your screen doesn't show anything
of that.

**Comment by stsp** [comment]
```
C:\>bin\mode
Screen size: 80 columns, 25 rows, mode 3, font height 16
C:\>bin\mode mono
C:\>bin\mode
Screen size: 80 columns, 25 rows, mode 7, font height 16.
```

So `mode mono` just switches to mode 7.

**Comment by stsp** [comment]
You can do `mode mono,43` also in dosemu,
but it won't stretch screen, and will instead use
small fonts. You can stretch it with mouse, but
it doesn't look pretty.

**Comment by emendelson** [comment]
You're right: I simply forgot that my mono-capable 43-line DOSBox modes were simply hacked mode 7. This is the code in int10_modes.cpp:

`#if FORTY3`
`{ 0x007  ,M_TEXT   ,720 ,688 ,80 ,43 ,9 ,16 ,8 ,0xB0000 ,0x4000 ,100 ,688 ,80 ,688 ,0	}, /* emendelson */`
`#else`
`{ 0x007  ,M_TEXT   ,720 ,400 ,80 ,25 ,9 ,16 ,8 ,0xB0000 ,0x1000 ,100 ,449 ,80 ,400 ,0	},`
#endif`

Whatever vDos does makes mode mono possible at any text size, but vDos is not a hardware-emulator, more of environment for running DOS software.

**Comment by stsp** [comment]
I think even in vDos you just hack
on mode 3 or 7. Allowing a custom
mono modes is what only dosemu2
does.
Of course we can extend xmode so
that `xmode mono,43` will give you
a larger screen rather than a smaller
font as `mode mono,43` does.

**Comment by emendelson** [comment]
> Of course we can extend xmode so
that xmode mono,43 will give you
a larger screen rather than a smaller
font as mode mono,43 does

That would be very nice to have...

**Comment by emendelson** [comment]
Someone reported that dosemu2 is now in the official Ubuntu repository. Am I right to guess that the official repository version will always be older than the one from ppa:dosemu2/ppa, so the ppa repository is to be preferred?

**Comment by skitt** [comment]
> Someone reported that dosemu2 is now in the official Ubuntu repository.

Not according to the Ubuntu repository: https://launchpad.net/ubuntu/+source/dosemu2

**Comment by andrewbird** [comment]
Not sure how accurate this site is but according to it only Arch has packaged it.
https://repology.org/project/dosemu2/versions

**Comment by stsp** [comment]
I think also gentoo does, but maybe
its something PPA-alike there.

**Comment by emendelson** [comment]
The user who reported that dosemu2 is officially available in Ubuntu was clearly wrong. I've told him so.

**Comment by stsp** [comment]
> I wrote that you don't recommend copying the full conf file, but that I find it easier to work with it.

The problem with your approach is
that it withdraws the flexibility.
Currently dosemu.conf changes: new
options added, old ones removed, comments
are updated. But the user doesn't and
shouldn't notice.
If you make a local copy, then the user
is doomed to play with old options and/or
outdated comments.
The fewer info we export to user, the
more flexible is the scheme.

Maybe you can instead come up with
the sed script that will copy the needed
paragraph (option and its comments)
from main dosemu.conf to the user's.
That way user will only get the options
he needs, and with comments.

**Comment by emendelson** [comment]
Understood. It shouldn't be too hard to come up with a sed script like the one you describe.

**Comment by j2969719** [comment]
bit offtopic but can someone tell how i can correctly set country code?
took the country.sys from freedos and put it in a drive_c folder
created userhook.sys with `country=7,,c:\country.sys` line

but when running dosemu i only get c:\country.sys not found message

**Comment by emendelson** [comment]
By the way, I tried writing a sed script that would copy the text around a specified string and paste it into the user conf file, but I'm not expert enough to get it to work correctly. Will try again this week.

**Comment by stsp** [comment]
sed is an exceptionally bad tool for
multi-line patters. You would probably
have better luck with awk.
