### ISSUE TITLE
umask problem

### ISSUE THREAD

**Issue by jllysoft** [dosemu2/dosemu2#1680]
**Describe the bug**
When creating file, the umask setting doesn't effect the file permissions as expected.
The goal is in multiuser environment different users should be able to write the same file with the umask 0007 setting.
The situation now: you create the file with umask 0007 and file'll be created with mod 640 (rw-r---) and not with the expected 660.

**To Reproduce**
- set the umask 0007
- launch command: dosemu.bin -X 
- in dosemu window launch command: dir >pp
- in linux you check the permissions: ls -l pp
-rw-r----- 1 1f911 users 16179 jún   15 09:58 pp

If you set umask 0077, you get the same result (mean the same permissions: 640).
If you set umask 0002 or 0022 or 0222, then the file permissions will be 644 in all cases.

**Attach program/game binaries or provide an URL**

**Attach the log**

**A regression?**
In 32 bit dosemu 1.4.0.7+20130105+b028d3f-1 it works.

**Additional info**
Linux distr: xubuntu 20.04 64 bit, 
dosemu2: 2.0~pre9-7439-396b932ef+202205300317~ubuntu20.04.1

**Comment by stsp** [comment]
Should now be fixed.
Forgotten artefact from pre-xattrs
code.

**Comment by jllysoft** [comment]
The package build has been failed for ubuntu version 20.04 since june 12.

**Comment by stsp** [comment]
Please mark this bug:
https://bugs.launchpad.net/bugs/1979054
as affecting you.
We'll try to switch to clang.

**Comment by jllysoft** [comment]
After upgrade umask problem still exists.
Current versions:
comcom32   0.1~alpha3-163-a33cf51+202201011631~ubuntu20.04.1              
dosemu2     2.0~pre9-7487-5d3ea0dbe+202206200031~ubuntu20.04.1     
fdpp             1..6-1222-068b5ee+202206111446~ubuntu20.04.1                    
Started with setting umask 0007, the files resulted were mod 640.
Enclosed boot.log
[boot.log](https://github.com/dosemu2/dosemu2/files/8939736/boot.log)

**Comment by stsp** [comment]
Well, there are no more `umask()`
calls in the code that I could find.
So I am quite sure the problem is
solved.

> Started with setting umask 0007, the files resulted were mod 640.

Why is this wrong?
Umask removes certain mode
bits, so in this case mode has
0 at the end, as 7 in umask
zeroed that octet?

**Comment by andrewbird** [comment]
> Why is this wrong?

I believe it's correct. Umask can only take away, but not enforce. So if the application tries to create a file with 0644 and his 0007 umask is applied, the result is 0640. That being said, most apps would try to create a file with 0666 and in that case he'd get what he expects.

**Comment by andrewbird** [comment]
It seems to be here, but what the motivation for this was, I don't know.
https://github.com/dosemu2/dosemu2/blob/d13e41e3451ac71fe681d40d1b1e69c0724c940f/src/dosext/mfs/mfs.c#L1377-L1379

**Comment by stsp** [comment]
So should we create files
with 0666 by default? And
expect the user to set the
valid umask?
Do you think this is a sane
thing to do?

Anyone?

**Comment by stsp** [comment]
```
$ umask
0002
```

So the distros already set
umask to 2, which would give
us 0664.
So should we indeed do that?

**Comment by andrewbird** [comment]
fopen() has this on its man page, so it seems like a sane default.
~~~
Any created file will have the mode S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH (0666), as
modified by the process's umask value (see umask(2)).
~~~

**Comment by skitt** [comment]
The POSIX default is 0666 (well, it’s slightly more complex than that, see https://unix.stackexchange.com/a/287281/86440 but we can ignore that here). With a typical default `umask` of 0022 or 002, that produces files with 0644 / 0664 permissions respectively.

**Comment by stsp** [comment]
Done then.
