### ISSUE TITLE
mmap(): Operation not permitted / ERROR: shared memory map failed 0xffffffffffffffff 0x7fcf6d070000, exiting

### ISSUE THREAD

**Issue by mkst** [dosemu2/dosemu2#2159]
**Describe the bug**
We are seeing the latest version of dosemu crash out as part of our [CI](https://github.com/decompme/decomp.me/pull/1100/checks).
```
$ dosemu -v
dosemu2-2.0pre9
Revision: 7076
```
```
$ cat dosemurc 
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "emulated"
$_sound = (off)
$_hogthreshold = (0)

$_cpuspeed = (333.333)
$_pci = (off)
$_rdtsc = (off)
$_term_color = (off)
$_ipxsupport = (off)
$_pktdriver = (off)
```

Command/flags used
```
HOME="." /usr/bin/dosemu -dumb -f ${COMPILER_DIR}/dosemurc -K . -E "CC1PSX.EXE -quiet ${COMPILER_FLAGS} -o object.os object.oc"
```

**To Reproduce**
Steps to reproduce the behaviour:
- unsure, i'll try to get a more simple reproducible example without you having to spin up decomp.me

**Attach program/game binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.

**Attach the log**

```
dosemu2 2.0pre9 Configured: 2024-02-21 19:03:22 +0000
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FDPP kernel 1.7 [GIT: ] (compiled Feb 20 2024)
Kernel compatibility 7.10 - clang - FAT32 support

Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

 - InitDisk: 
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB

                                                                               
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Process 0 starting: E:\command.com /e:512 /k %FDPP_AUTOEXEC%

can't create dir /var/run/user/1000/dosemu2: No such file or directory
ERROR: Unable to open console or check with X to evaluate the keyboard map.
Please specify your keyboard map explicitly via the $_layout option. Defaulting to US.
Can't create debugger pipes, dosdebug not available
ERROR: unknown window sizes li=0  co=0, setting to 80x25
mmap(): Operation not permitted
ERROR: shared memory map failed 0xffffffffffffffff 0x7fcf6d070000, exiting
ERROR: DPMI: leaked 81344 bytes (main pool)
```

**A regression?**
We successfully ran dosemu 3 days ago as part of our CI.

**Additional info**

We run dosemu within an nsjail environment inside Docker.

**Comment by stsp** [comment]
> ERROR: DPMI: leaked 81344 bytes (main pool)

Leak should now be fixed.
As for the actual problem, please
show the output of
`df /dev/shm`

**Comment by mkst** [comment]
Cool - i'll try again once the fix is build/released.

```
$ df /dev/shm
Filesystem     1K-blocks  Used Available Use% Mounted on
shm                65536     0     65536   0% /dev/shm
```
**Edit:**
We use other programs within this environment that call `mmap`, so it's weird that dosemu fails but not them :thinking:

**Comment by stsp** [comment]
OK, 65Mb is quite small, but should
still work. Now can you create files
there?
`echo aaa >/dev/shm/a`
what is the output?
Then you can erase the file with
`rm /dev/shm/a`

**Comment by mkst** [comment]
Yup, this user can write to /dev/shm. Let me restart the container with a larger /dev/shm.
```
user@03051c2f104c:/backend$ echo "foo" > /dev/shm/a
user@03051c2f104c:/backend$ stat /dev/shm/a
  File: /dev/shm/a
  Size: 4         	Blocks: 8          IO Block: 4096   regular file
Device: 6fh/111d	Inode: 14          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    user)   Gid: ( 1000/    user)
Access: 2024-02-21 21:01:48.827285592 +0000
Modify: 2024-02-21 21:01:48.827285592 +0000
Change: 2024-02-21 21:01:48.827285592 +0000
 Birth: 2024-02-21 21:01:48.827285592 +0000
user@03051c2f104c:/backend$ rm /dev/shm/a 
user@03051c2f104c:/backend$ stat /dev/shm/a 
stat: cannot statx '/dev/shm/a': No such file or directory
```
**Edit**: mmap error remains with 1GB /dev/shm.

**Comment by stsp** [comment]
Please show the output of
`mount |grep shm`

Yes, `mmap(): Operation not permitted`
doesn't sound like a size problem, so you
may as well consider returning to 64Mb. :)

**Comment by mkst** [comment]
Has the mmap behaviour changed recently in dosemu?
```
user@8d2c20b29022:/backend$ mount | grep shm
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1048576k,inode64)
```

**Comment by stsp** [comment]
Yes, there were some changes.
"noexec" is a problem, try removing
it. If that works, I'll try to add the
work-around.

**Comment by mkst** [comment]
remounted:
```
$ mount | grep shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,relatime,size=131072k,inode64)
```
different errors:
```
can't create dir /var/run/user/1000/dosemu2: No such file or directory
ERROR: Unable to open console or check with X to evaluate the keyboard map.
Please specify your keyboard map explicitly via the $_layout option. Defaulting to US.
Can't create debugger pipes, dosdebug not available
ERROR: unknown window sizes li=0  co=0, setting to 80x25
ERROR: touched jit-protected page
ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

ERROR: touched jit-protected page
ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

ERROR: /usr/lib/dosemu/libplugin_dj64.so: libdjdev64.so.0.1: cannot open shared object file: No such file or directory
ERROR: CS selector invalid: 0x0217, type=0 np=0
```

**Comment by stsp** [comment]
Most of these problems are already
fixed. But there are certain problems
with launchpad (it randomly fails builds
and spends hours before publishing
new packages), so I am still struggling
with landing the packages.

I think if you run
`ldconfig`
then some of the above problems will
disappear by themselves, so can you
try that before the updates are ready?

**Comment by stsp** [comment]
libdjdev64.so.0.1 is supposed to be in
`/usr/lib`, so
`ls -l /usr/lib/libdjdev64.so.0.1`
will also help.

**Comment by mkst** [comment]
Struggling here.. ldconfig wants to write to `/etc/ld.so.cache~` and im not root (don't have sudo). I tried running it with a different location for the cache, didnt seem to make a difference.

What is the installation candidate for libdjdev64.so.0.1?

**Comment by stsp** [comment]
If you are not root, then how are you
updating the packages?
dj64 package provides libdjdev64.so.0.1,
do you have it installed?
It is in "Recommends", not "Depends",
so maybe this is why you don't get it as
a dependency...

**Comment by mkst** [comment]
The docker image is built as `root` and then switches to a non-root user so the running container doesnt have root.

I've managed to install dj64 but now I see
```
ERROR: touched jit-protected page
ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

ERROR: touched jit-protected page
ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

dj64init_once failed
```

**Comment by stsp** [comment]
There are some version mismatches,
which would be solved once all the
updates are published by LP.

As for the noexec problem, it is a
re-incarnation of #936 
I have this e-mail from @redpig
who worked on solving this in a kernel
(only relevant details extracted from
the private e-mail):

```
I did go through some alternatives!  I think I wired up a "halfexec" mount options, much like noprotexec,
but it was a pain to touch all the mount options for updating :)  I think tracking O_CREAT|O_TRUNC would
be doable (either with an extra bit or via lsm hooks).

On Sat, Oct 12, 2019 at 7:06 AM stsp <[stsp2@yandex.ru](mailto:stsp2@yandex.ru)> wrote:

    Hi Will!

    Investigating this report:
    https://github.com/stsp/dosemu2/issues/936
    I've found your patch here:
    https://lwn.net/Articles/455256/

    It doesn't seem to be applied.
    What was the problem, and what's the current
    status of it?
    By the way, have you considered the alternative
    approaches? For example:

    - One can add another mount option, say, "noprotexec",
    which will disable mmap/mremap(PROT_EXEC).
    In this case the normal "noexec" will only block execve(),
    which is what it always did.

    - If we are theoretizing, perhaps the one can track
    if the file was opened with O_CREAT|O_TRUNC, and
    only in that case allow mmap() to ignore mnt_noexec?

    - If we are fantasizing, perhaps the new syscall can
    be added for shm_open() (rather than just the libc
    wrapper), and a new fs option "shm" that will prevent
    open() on that FS while still allowing shm_open()?
    This will probably be the most secure approach, as
    it will mean you can't even copy any file into /dev/shm
    by normal tools, not to speak about running it with ld.so.

    What do you think?
```

I wonder what is the status of that work
today? But I suspect, not much different
from 5 years ago. :)

**Comment by stsp** [comment]
I think all updates have landed.
Don't forget to do
sudo apt-get update
to refresh the metadata cache.

**Comment by mkst** [comment]
Looks to be fixed! Thanks for the fast turnaround!

**Comment by mkst** [comment]
Ah, I believe it still fails if /dev/shm is mounted with noexec... or rather it's hanging. How to avoid this 'press any key' prompt?
```
Process 0 starting: E:\command.com /e:512 /k %FDPP_AUTOEXEC%

Shell E:\command.com exited, press any key...
```

**Comment by stsp** [comment]
Yes, that is so.
Doesn't work with noexec right now.

**Comment by stsp** [comment]
Lets keep this open, as I am sure
this will affect other people.

**Comment by stsp** [comment]
Do you have also /tmp mounted
with noexec?

**Comment by stsp** [comment]
If I am to work on this on the linux
kernel side (hope not!), I'd come up
with something like this proposal:

- make shm_open() a syscall, unaffected by `noexec`
  (currently shm_open() is a library wrapper around open())
- add a new mount option, say `noio`, that disables
  open(), read() and write() syscalls on that partition.

This way the only possibility to work with /dev/shm
would be a shm_open()+mmap() combo.
Of course the malicious loader can still use
that to write and execute arbitrary data. But
the malicious loader can as well use read()
into anonymously mapped executable memory,
bypassing `noexec` right now (but not with the
aforementioned `noio` flag).

@redpig, @fenrus75, @kees - what do you think?
Can something like that be considered?
Btw, since `noexec` only fights the normal
loader (not a malicious one), I wonder why
(and when?) the mprotect(PROT_EXEC)
work-around was disallowed. Does anyone
have the pointers why have that happened?

**Comment by mkst** [comment]
> Do you have also /tmp mounted with noexec?

`/tmp` is mounted with exec privileges

**Comment by jschwartzenberg** [comment]
> `ERROR: /usr/lib/dosemu/libplugin_dj64.so: libdjdev64.so.0.1: cannot open shared object file: No such file or directory`

What's up with that error? I don't have `libdjdev64.so.0.1`, but `libdjdev64.so` after `make install`.

**Comment by stsp** [comment]
```
$ ls -l libdjdev64.so 
lrwxrwxrwx 1 stas stas 17 мар  6 08:45 libdjdev64.so -> libdjdev64.so.0.1
```
So you should have both, because
one is just a symlink.

**Comment by stsp** [comment]
I think this is now "fixed"...
in a sense that comcom64 now uses
/tmp instead of /dev/shm.
If some idiot adds `noexec` also on
/tmp, it'll break forever.

**Comment by mkst** [comment]
Me again. I'm hitting permission denied on `shm_open()` when trying to run an old MSVC CL.EXE inside of Docker.

```
shm_open(): Permission denied
ERROR: shared memory unavailable, exiting
dosemu2.bin: ./build/../src/dosext/dpmi/msdos/msdos_ldt.c:89: msdos_ldt_init: Assertion `!err' failed.

Aborted (Signal sent by tkill() 340 999)
```

Any idea how to troubleshoot? 

I'm using 
```
dosemu2/jammy,now 2.0~pre9-8910-d87e5b163+202407311302~ubuntu22.04.1 amd64 [installed]
  fast and secure DOS emulator
``

Outside of Docker everything is OK. 

**Edit:**

I tried setting `$_mapping = "mapshm"` in my rc file to no avail

**Comment by stsp** [comment]
By mapping tmpfs to /dev/shm?

Понедельник, 26 августа 2024 г получено от Mark Street:

**Comment by mkst** [comment]
Yeah:

```
$ mount | grep dev/shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,relatime,size=65536k,mode=700,uid=1000,gid=1000,inode64)
```

I am still able to run the binaries were erroring out before (i.e. the ones that caused me to create this issue in the first place), but CL.EXE is not playing ball.

**Edit:**

Also tried latest dosemu2 (20240825):
```
dosemu2/jammy,now 2.0~pre9-8980-2782b353f+202408251417~ubuntu22.04.1 amd64 [installed]
  fast and secure DOS emulator
```

**Comment by stsp** [comment]
Then update the ticket with new info or create another one.

Понедельник, 26 августа 2024 г получено от Mark Street:
