### ISSUE TITLE
tests are failing without a log?

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2217]
Hi Andrew, what can this be?
https://github.com/dosemu2/dosemu2/actions/runs/9354576590/job/25747724955

**Comment by andrewbird** [comment]
I think Github cancelled it after it was running for 2 hours.
```The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.```
I suspect that PPDOS is not booting, and the test suite waits for each test until they timeout.

**Comment by stsp** [comment]
Ah, I see, it might be comcom64 not
booting, waiting for a key-press to exit.
That could happen if it wasn't re-built
with the latest dj64 update. I attach such
a defective comcom64 here for you to
reproduce the situation:
[comcom64.exe.gz](https://github.com/user-attachments/files/15543904/comcom64.exe.gz)

Now obviously there are problems:
- no logs and stdouts are shown
- tests are not aborted after a failure

**Comment by stsp** [comment]
After you take a look into a test part,
I'll need to make a change so that the
keypress is not waited for, if comcom
exited with non-zero exit status.

**Comment by stsp** [comment]
Also the exit status should propagate
to dosemu exit status, so that you can
see the comcom's failure in your testing
frame-work.
I already have these changes ready,
but not pushing them to not spoil for
you the reproducer of the yesterday's
problem.

**Comment by andrewbird** [comment]
>no logs and stdouts are shown

In the event that Github kills the job, I have no control over what gets collected.

>tests are not aborted after a failure

That I can do something about. What I propose is that I create a special first test that must pass or the remaining set of tests are cancelled. With this the 2 hour Github limit won't be hit, no kill will occur, and we'll get the logs.

I have to go out now, but will try to get something done this evening.

**Comment by stsp** [comment]
> In the event that Github kills the job, I have no control over what gets collected.

Well, github killed the job after many
tests already failed. How about printing
the logs after each failed test, rather
than at the end?

> What I propose is that I create a special first test that must pass or the remaining set of tests are cancelled.

But I don't understand since when this
stopped to be the case. IIRC the tests
were aborting on the first failed one.
Which is exactly what you propose now,
except w/o any need of special-casing
the first one. Any test can/should abort
the subsequent ones.
It would be great if then it proceeds to
testing the next DOS, so that we can see
if other DOSes still boot. That would
work in this case, as other DOSes do not
use comcom64.

**Comment by andrewbird** [comment]
> But I don't understand since when this
stopped to be the case. IIRC the tests
were aborting on the first failed one.

No that wasn't the case. Python unittest performs all the tests first to create the summary page, then if any have failed the details are printed out afterwards. Otherwise the summary gets lost in a sea of failure log. I can't point you to an old test run on github actions as they are only kept for 3 months, but just think to yourself how many times has 'all the tests are failing' been said, and how many 'a test is failing' in comparison.

I can change it to 'failfast' which does as you describe, i.e. any failure terminates the test run. As a by-product you get your failure log (but only one) printed directly after the test fail. Of course having only one failure removes any chance to spot patterns e.g. does this failure on MFS affect both SFNs and LFNs.

As you can probably tell I'd prefer to add the single sanity test with 'failfast' that I proposed earlier, but 'failfast' on any is easier. You choose? 

> It would be great if then it proceeds to
testing the next DOS, so that we can see
if other DOSes still boot.

I can do that, but bear in mind that then the test summaries and test failures will be separate too.

**Comment by stsp** [comment]
> Of course having only one failure removes any chance to spot patterns e.g. does this failure on
> MFS affect both SFNs and LFNs.

Perhaps this can be left for the
optional tags, like `[full CI]` or alike?

> but 'failfast' on any is easier. You choose?

Yes, I think `failfast`, print the log and go
to the next DOS testing is a good default.
Everything else can just be enabled by an
optional tags.

> I can do that, but bear in mind that then the test summaries and test failures will be separate too.

Well there would be only 2, as IIRC we
only test fdpp and ms-dos. So not a big
problem.

**Comment by stsp** [comment]
Thanks!
But I am not entirely sure this
particular ticket is fixed. You
tried crashing comcom64 combo,
but there is another one: when
dj64 is up-to-date, but comcom64
is not. In that case there is no crash,
but instead wait for a keypress,
which leads to a CI timeout.
Could you please check that this
is also addressed?
You just need to update dj64dev
w/o updating comcom64, or you
can update everything and take
comcom64 from this ticket.

**Comment by andrewbird** [comment]
> You just need to update dj64dev
w/o updating comcom64, or you
can update everything and take
comcom64 from this ticket.

Funny thing, even after updating I can't seem to find comcom64 (from PPA) when running in the devel directory, so I still get the message.
~~~
ERROR: Neither freecom nor comcom32 installation found.
Use DOSEMU2_EXTRAS_DIR env var to specify location of freedos
or DOSEMU2_COMCOM_DIR env var for alternative location of comcom32
Bad or missing Command Interpreter: command.com
~~~

**Comment by bolle732** [comment]
I had the same trouble yesterday too. Rebuilded everything djXX, comcom64, fdpp and dosemu2. And after that I had todo a manual execution of `ldconfig`. After that all is working again.

**Comment by andrewbird** [comment]
Thanks @bolle732, your description helped me to discover that I had a missing build dependency package `djdev64-dev`. I'll now try to test out the test scenario @stsp asked me too!

**Comment by andrewbird** [comment]
So timeout (triggered by the comcom64.exe above) also does cause the fastfail.
~~~
ajb@calypso:/clients/common/dosemu2.git$ env SKIP_EXPENSIVE=1 test/test_dos.py PPDOSGITTestCase
libi86-testsuite-ia16-elf not installed - skipping those



Test PP-DOS-GIT  Command.com keyword exist                                       ... 
  test_command_com_keyword_exist (__main__.PPDOSGITTestCase.test_command_com_keyword_exist) [Subtest 00] ... FAIL
FAIL (one or more subtests)
    [Subtest 00]                                                                 ... FAIL

======================================================================
FAIL: test_command_com_keyword_exist (__main__.PPDOSGITTestCase.test_command_com_keyword_exist) [Subtest 00]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 3158, in test_command_com_keyword_exist
    self.assertRegex(results, r"(?m)^%02d_True.*" % i)
AssertionError: Regex didn't match: '(?m)^00_True.*' not found in 'Timeout'

----------------------------------------------------------------------
Ran 1 test in 10.141s

FAILED (failures=1)
~~~

~~~
ajb@calypso:/clients/common/dosemu2.git$ cat test_dos.PPDOSGITTestCase.test_command_com_keyword_exist.xpt
dosemu2 2.0pre9-dev-20240605-2003-ge19a90b72 Configured: 2024-06-05 17:26:33 +0000
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FDPP kernel 1.7 [GIT: 1.7-146-ga6902e70] (compiled Jun  5 2024)
Kernel compatibility 7.10 - clang - FAT32 support

Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
G: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled                                           
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Process 0 starting: C:\command.com /e:2048 /k %FDPP_AUTOEXEC% /M2
dj64: load failure

Shell C:\command.com exited, press any key...
~~~

**Comment by stsp** [comment]
Ok, thanks guys!
I added the hints about ldconfig now for
those who still build everything by hands.
I didn't know such a brave ppl still exist. :)

Also the mistaken wait for a keypress
should no longer happen, plus the exit
code of comcom64 now propagates to
dosemu2.

**Comment by stsp** [comment]
@bolle732 with recent changes you
may get build failures until you re-build
thunk_gen.
Andrew is likely unaffected, as I think
he only builds dosemu2 itself, with the
rest coming from PPA.

This change was needed to finally document
the build process under dj64. The culprit
was the thunk_gen-related mess in a
makefile, which can't be documented.
But now it is just included from the
thunk_gen-provided file, so all to document
related to thunk_gen, is an include line. :)

**Comment by andrewbird** [comment]
> Andrew is likely unaffected, as I think
he only builds dosemu2 itself, with the
rest coming from PPA.

I build dosemu2 and fdpp, the rest as you mentioned are from the Ubuntu PPA.

**Comment by stsp** [comment]
fdpp's meson build is unaffected as
I can't find the include directive in meson.
So I don't know if with meson it would be
possible to move all the build ugliness to
thunk_gen, leaving the main file small and
simple.

If you use makefile-based build, then you
need to update thunk_gen first.

**Comment by andrewbird** [comment]
I use the meson build for fdpp.

**Comment by bolle732** [comment]
@stsp @andrewbird 
Thanks to you both for the hints and updates.

To compile DOSEmu2, FDPP and COMCOM64 I use this additional packages / tools by Stas from Github:
```
dj64dev
djstub
nasm-segelf
smallerc
thunk_gen
```
Yes, the way with the PPA could make it a little bit easier. But the above "helper-repos" are so small and fast to compile.

**Comment by stsp** [comment]
smallerc is not mine. :)
In fact, I think its already in debian, as
well as in the ubuntu oracular:
https://launchpad.net/ubuntu/+source/smallerc
Unlike all my pseudo-compilers
that actually work on top of clang
or gcc, smallerc is a real C compiler
written from scratches.

@skitt how goes adding nasm-segelf? :)
It shouldn't be any problematic, or is it?

**Comment by stsp** [comment]
Now there is some problem with
dosemu_tap_interface.sh:
https://github.com/dosemu2/dosemu2/actions/runs/10240081305/job/28326421454
Andrew?

**Comment by stsp** [comment]
Ok, I simply commented out the
iface removal then. Not sure why
that can fail, but it seems like it did.
