### ISSUE TITLE
Another ANSI.SYS not detected 

### ISSUE THREAD

**Issue by nelgin** [dosemu2/dosemu2#2245]
I have another case here of ANSI.SYS not detected, even tho it's loaded by way of NANSI.SYS

![image](https://user-images.githubusercontent.com/6232589/350605931-6494219f-ff5b-49fe-8637-56143aba1f30.png)

using default /etc/dosemu/dosemu.conf (cos I don't want someone getting all pissy with me for having crap all over the place ;) ). except for $_hdimage assignment.

my .dosemu/drive_c has userhook.sys which loads NANSI.SYS

When I run "zwordz zwordz.cfg" it thinks for a minute before telling me "Sorry, Z-Wordz requires ANSI graphics capabilities". If you want to try and run the attached, you may want to edit zwordz.cfg to point to the included door.sys file. 

The zwordz.exe appears to be a self extracting zip. I used unlite to unpack it to zwordze.exe
[zwordz.zip](https://github.com/user-attachments/files/16317378/zwordz.zip)

_Originally posted by @nelgin in https://github.com/dosemu2/dosemu2/issues/1715#issuecomment-2240330881_

**Comment by stsp** [comment]
Image is not seen here.
Is it only me?

**Comment by stsp** [comment]
For me it just says "Error reading system file".
I suspect yet another bad test-case...
How much?

**Comment by nelgin** [comment]
Image not working for me either. Did you change zwordz.cfg line 1 to point to the directory where you uncompressed it so it can find door.sys ?

**Comment by stsp** [comment]
Of course not, as you haven't told me
to do so.
Now It reproduces.

**Comment by nelgin** [comment]
Which bit of "you may want to edit zwordz.cfg to point to the included door.sys file." didn't you read in my original report?  ;)

**Comment by stsp** [comment]
Well, there is a certain bug-reporting
template, which asks to provide all actions
as a steps. This is much more productive,
than to parse things like
"When I run "zwordz zwordz.cfg" it thinks for a minute before telling me "Sorry, Z-Wordz requires ANSI graphics capabilities". If you want to try and run the attached, you may want to edit zwordz.cfg to point to the included door.sys file."
But since you converted the discussion
to the bug, you bypassed the template.
I  probably have to prohibit converting
discussions to issues to everyone but
myself, but I don't think github has such
a config knob.

**Comment by stsp** [comment]
So its obviously trying to detect ANSI
via com1 somehow. It doesn't send any
escapes to screen, but instead is trying
to poke into com1, which is disabled.
So either it is misconfigured, or it is not
intended to detect ANSI in local mode.
There are simply no escape codes sent
via int10, so it isn't trying.

**Comment by nelgin** [comment]
I guess one option would be to patch the code so it always thinks that ANSI is enabled? In the BBS I have an option to require the user to have logged in with an ANSI terminal before running a game so that is covered.

I think that's a bit beyond my ability so maybe I'll just move on. I appreciate you looking at it.

**Comment by stsp** [comment]
If you can get it to pass the detection
in remote mode, then it might be relatively
simple to patch the program by looking
at what exactly does it expect to get from
the serial port, and where does it check
the result.

**Comment by nelgin** [comment]
Unfortunately I get the same when running via the BBS or local mode. 

Is there some way I could connect a virtual com port or something to see what it is sending? At least I might be able to figure what it's asking so I can try to send a response.

**Comment by stsp** [comment]
`-D9+s`.

**Comment by nelgin** [comment]
Nothing much in the log. Maybe I need to enable a com port? I don't have any defined, I guess, since I'm using the default dosemu.conf

**Comment by nelgin** [comment]
I'm trying to do this...

in ~/.dosemu/dosemurc I have $_com1 = "/dev/ttyS20"

In linux:

socat PTY,link=/dev/ttyS20,raw,echo=0,b9600 PTY,link=/dev/ttyS21,raw,echo=0,b9600

then I did a chmod 777 /dev/ttyS20 /dev/ttyS21 to make sure there were no permissions errors

On a different terminal set the baud rate to 9600 on both ttyS20 and ttyS21.

Then cat /dev/ttyS21 so I can see what's coming out via the com port. I run dosemu2 but there doesn't appear to be a com port defined. MODE just returns printer port 1, 2, and 3 and virtual printer port 4. Looking at memory location 40:0 I get 00 00 where com1 is supposed to be. Not sure if that's normal for the virtual environment. 

But anyway, bottom line is I don't seem to have a com port even though $_com1 is defined.

**Comment by nelgin** [comment]
Additional. The logs show

Warning: SERIAL $Id$
SER: Running serial_init, 0 serial ports

**Comment by stsp** [comment]
You were likely getting an error in the
log about tty locks. I disabled locks by
default now, and you can just set
`$_ttylocks = ""` to not wait for an update.

**Comment by nelgin** [comment]
I added $_ttylocks = "" to my .dosemurc file but no joy.

SER: directory /var/lock namestub LCK.. binary No

Is all I see in the logs with anything to do with "lock"

mode com1: says com1 is not existing on this PC.

**Comment by nelgin** [comment]
It looks like ~/.dosemu/dosemurc isn't being read.

Once I put $_com1 and $_ttylocks config into the /etc/dosemu/dosemu.conf then the serial port is showing up.

**Comment by nelgin** [comment]
I spoke too soon.

MODE COM1: responds with

*** SERIAL PORT 1 STATUS ***
Port status: [ xmit-shift-empty xmit-hold-empty ]

and any attempt to redirect output to com1: ends up writing a file in the current drive.

**Comment by stsp** [comment]
> and any attempt to redirect output to com1: ends up writing a file in the current drive.

No idea why you have that.
I do `echo aaa>com1` and that works.
There were problems, for example doing
`type com1` didn't work, and is now fixed.
That seems to be a kernel bug, it started
to return wrong errno from failed ioctl(),
so I just removed an errno check.
But `com1` _file_ was never created for me,
even before the fix.

**Comment by nelgin** [comment]
OK...I didn't update but I fixed the issue so the next problem is, the game reports "carrier lost" so I have to somehow fake a CD signal on the serial port? Urgh.

**Comment by stsp** [comment]
Понедельник, 22 июля 2024 г получено от nelgin:
> OK...I didn't update but I fixed the issue

How?

> so the next problem is, the game reports "carrier lost"

Will likely be fixed by an update.

**Comment by nelgin** [comment]
How? 30 years of forgotten dos knowledge. I was using, as I said, com1: rather than com1. Once the serial port showed up and I used com1 then it worked :)

Will look out for the next update. Thanks.

**Comment by stsp** [comment]
Update is already there, no?

**Comment by nelgin** [comment]
No idea. I thought I'd see a commit or something. Let me update and report back.

**Comment by nelgin** [comment]
2.0~pre9-8867-996c1912a+202407211747~ubuntu22.04.1 installed but still getting "lost carrier".

when I run mode com1: when dosemu starts I see:

```
*** SERIAL PORT 1 STATUS ***
Port status: [ xmit-hold-empty data-received CD DSR CTS ]
```

After the program exits it has changed to

```
*** SERIAL PORT 1 STATUS ***
Port status: [ xmit-hold-empty data-received ]
```

Other than trying this on a system with an actual serial port, I'm not sure what else to try.

**Comment by stsp** [comment]
Maybe remote end closed the port?
Try `cat` on that port after CD lost.

**Comment by nelgin** [comment]
nada.

I have a null modem between my Winzers pc and Linux box under my desk so I'll give it a try later to see if I can get anything out of it that way.

I appreciate the help, as always.

**Comment by stsp** [comment]
Not quite sure if you tried `cat` or not.
Of course with real serial port you'll
get different results, but socat's PTY links
are well supported too (unless there is a
bug).

**Comment by stsp** [comment]
I suppose initially `cat` should stuck
waiting for an input, but when CD lost,
`cat` will just exit.

**Comment by nelgin** [comment]
I tried to cat /dev/ttyS21 both before dosemu runs and after but nothing. I do get output if I redirect com1 to a file in dosemu.conf but I still get lost carrier. 


sudo socat PTY,link=/dev/ttyS20,raw,echo=0,b96 PTY,link=/dev/ttyS21,raw,echo=0,b9600              

I tried various tty options like icanon=1 and I have tried clocal and -clocal using stty but nothing. Let's wait until I can feck around with a proper serial port later today.

**Comment by stsp** [comment]
> I tried to cat /dev/ttyS21 both before dosemu runs and after but nothing.

"but nothing" is not an answer.
What exactly does it do before and
after?

> I tried various tty options

socat options are irrelevant, please get
back to the "last good" ones.

**Comment by nelgin** [comment]
I've setup the files on my box at home with a USB serial port.

While I am still getting the lost carrier issue, I do see that characters are being sent to the /dev/ttyUSB0 device. Unfortunately, nothing useful 0x1b 0x0c

So. still need a way to get dosemu to force a carrier detect somehow since there's no way for the software to ignore it.

**Comment by stsp** [comment]
Since you went into "not doing what you say" mode again, this can easily be my last posting to that thread.

Понедельник, 22 июля 2024 г получено от nelgin:

**Comment by nelgin** [comment]
I've moved on from that box to one with a real serial port, however since you are insisiting...

> socat options are irrelevant, please get
> back to the "last good" ones.

There are no "last good" ones. Whatever I try, I still get "lost carrier" 

> "but nothing" is not an answer.
> What exactly does it do before and
> after?

$ cat /dev/ttyS21


Nothing...just sits there. Absolutely nothing. 

Having said that, if there is a character code, I probably wouldn't see it. If I cat /dev/ttyS21|hexdump -c then nothing. As in...nothing.

I changed $_com1 = "/tmp/serial"

but it just writes a 0 length file when I run the game.

Not sure what else to tell you, specifically.

**Comment by stsp** [comment]
"Sits there and does nothing" is fine.
Now please do the same after carrier is lost. E.e. make sure under dosemu2 that its lost, exit dosemu2 and run cat on the port where dosemu2 reported no CD.
What does it do then?

Понедельник, 22 июля 2024 г получено от nelgin:

**Comment by nelgin** [comment]
After running the game and getting carrier lost, I exit dosemu back to the linux prompt. I did a cat of both /dev/ttys20 and ttyS21 and piped through hexdump -c to see if anything was printed and there is nothing. It just sits there and does nothing.

**Comment by stsp** [comment]
On both?
Do you mean the second end is not
used by any program at all?

**Comment by stsp** [comment]
> I've moved on from that box to one with a real serial port, however since you are insisiting...

With real serial port you can use
`statserial` to monitor DCD (and other
signals).

**Comment by nelgin** [comment]
Second end? You mean ttyS21? That's used by socat as part of the virtual terminal pair. 

I tried statserial on my system with com port and DCD is 0. I tried all the software tricks I can come up with both on the linux and windows side, short of shoving a voltage on pin 1. Maybe I can use my breakout box to jump from another pin. DTR maybe, just to see if I can pull it high, though I would need another serial cable since I forgot to get a spare with the box.

**Comment by stsp** [comment]
> Second end? You mean ttyS21? That's used by socat as part of the virtual terminal pair.

Seriously?
So you don't even communicate with anything?

**Comment by stsp** [comment]
@jordemort I think its your patch
7afc02fe5 that makes problems here.
I added the ability to re-open port, see
the commits referenced above.
But what I don't understand is how
exactly you produce that "close" event.
For example if I do
```
socat PTY,link=/tmp/ttyS20,raw,echo=0,b9600 PTY,link=/tmp/ttyS21,raw,echo=0,b9600
cat /tmp/ttyS20
```
then `cat` just sits there no matter what
I do on `ttyS21`. I can put `cat` also there
and then kill it (so that port closed), or I
can do `echo aaa >/tmp/ttyS21` and the
aforementioned `cat` shows "aaa" but
doesn't exit. Which means the 0 is never
read.
This is in contrast to the reporter, who gets
0 by some means he fails to explain.
Please explain the supposed semantic,
how to actually get this 0-read?

**Comment by stsp** [comment]
I rewrote the whole thing.
It now closes on any error.
Had to switch to blocking mode
to avoid extra errors (like EAGAIN),
which required even more changes.
Hope that works. :)

**Comment by stsp** [comment]
And I wasn't able to get 0 from tty,
no matter what I did. Even in PTY mode
when slave closes, I get -1 and EIO, but
never 0...
@jordemort were you using a pipe
instead of tty, or what?

**Comment by nelgin** [comment]
OK thanks.

Just to be sure, the problem we're trying to solve is that I get "lost connection" when running the game on the BBS. I need to resolve that so it doesn't require any sort of external feckering about, and we're fixing this to get over the ansi detection issue. Are we on the same page?

**Comment by nelgin** [comment]
Seems builds keep getting stuck

![image](https://github.com/user-attachments/assets/fa905329-7f18-4159-a134-2cbeea5ad36b)

**Comment by nelgin** [comment]
Maybe @andrewbird can do his magic...I'll check in when I wake up.

**Comment by jordemort** [comment]
@stsp My attention got diverted away from the project I needed that change for a a while ago, but yes I'm pretty sure I was using a pipe and not a TTY

**Comment by stsp** [comment]
What stuck is an arm64 build.
Updates of amd64 are working well.

**Comment by nelgin** [comment]
Last version I got from PPA was 
2.0~pre9-8889-38e81e5d2+202407231943~ubuntu22.04.1

running dosemu from the command line just hangs after

```
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
NANSI.sys 4.0b: New ANSI driver.  Copyright 1986-2003 Daniel Kegel
http://www.kegel.com/nansi/  <dank at kegel.com>
This is free software.  It comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU Public License; see http://www.gnu.org/ for details.
'''

Hmm...
ERROR: /usr/lib/dosemu/libplugin_term.so: /usr/lib/dosemu/libplugin_term.so: undefined symbol: base64_init_encodestate

SDL works fine, it opens in X with no problem, but not in terminal mode.


I created my virtual serial ports with socat.

mode com1: shows
![image](https://github.com/user-attachments/assets/2f59debc-3339-42ba-8837-d194e9e66672)

and I still get "carrier lost" when I try to run the game.
![image](https://github.com/user-attachments/assets/9e8bbfd5-d470-4ce4-be9d-7e6972c53411)

Nothing when I cat /dev/ttyS1. It just sits there and does nothing.

**Comment by nelgin** [comment]
Images still not showing up. Fantastic.

**Comment by stsp** [comment]
> ERROR: /usr/lib/dosemu/libplugin_term.so: /usr/lib/dosemu/libplugin_term.so: undefined symbol:
> base64_init_encodestate

Thanks, the fixed version will be available
in 10 minutes (except for the arm64, which
seems broken on LP these days).

Also the linux mail-list have indicated that
the tty return values are not going to be
changed to stay compatible with dosemu1:
https://lore.kernel.org/all/b6f4aa5c-10ba-411b-994b-6dbed2bf63db@yandex.ru/T/#m00a4aef53ec23c96802c226b5445e0dbc7423739
This means CD (and all other MSR signals)
will be broken on dosemu1 forever, which
is what you can tell when someone asks
"why not dosemu1".

> I created my virtual serial ports with socat.

So what is on the other end, eg ttyS21?
Are you going to talk to the unconnected
port forever?

Please attach the `-D9+s` log.

**Comment by nelgin** [comment]
OK. Good news...we're back to ansi detection failure when running from the command line, so we're past the carrier loss problem. 

This is running dosemu from the command line. It looks like it's trying to read the cursor position? ^[6n. 
```
00000000  0d 0a 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |..              |
00000010  20 20 20 20 20 20 20 20  20 20 20 20 54 68 61 6e  |            Than|
00000020  6b 20 79 6f 75 20 66 6f  72 20 75 73 69 6e 67 20  |k you for using |
00000030  5a 2d 57 6f 72 64 7a 20  0d 0a 0d 0a 20 20 20 20  |Z-Wordz ....    |
00000040  20 20 20 20 20 20 20 20  20 20 20 20 20 50 6c 65  |             Ple|
00000050  61 73 65 20 77 61 69 74  20 77 68 69 6c 65 20 45  |ase wait while E|
00000060  6e 64 20 4f 66 20 54 68  65 20 4c 69 6e 65 20 42  |nd Of The Line B|
00000070  42 53 20 72 65 6c 6f 61  64 73 2e 20 0d 0a 1b 5b  |BS reloads. ...[|
00000080  36 6e 1b 5b 36 6e 53 6f  72 72 79 2c 20 5a 2d 57  |6n.[6nSorry, Z-W|
00000090  6f 72 64 7a 20 72 65 71  75 69 72 65 73 20 41 4e  |ordz requires AN|
000000a0  53 49 20 67 72 61 70 68  69 63 20 63 61 70 61 62  |SI graphic capab|
000000b0  69 6c 69 74 65 73 0d 0a  0d 0a 0d 0a 20 20 20 20  |ilites......    |
000000c0  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
000000d0  20 20 20 20 20 20 20 20  50 72 65 73 73 20 28 45  |        Press (E|
000000e0  4e 54 45 52 29 20 74 6f  20 43 6f 6e 74 69 6e 75  |NTER) to Continu|

```

I'm attaching a dos boot log when the program is run via the BBS -D9+s tho not sure the +s is useful now.
[dosemu_boot.log](https://github.com/user-attachments/files/16364464/dosemu_boot.log)


The ttyS21 thing is just temporary to see what it's trying to send. The idea is to not have any other external program when run via the BBS. This now seem the case with the latest revision.

**Comment by stsp** [comment]
Is this a log???
Are you redirecting the serial port to
that log, or what?
So even if your program sends ^[6n
to serial port, then obviously there is
no one to reply, as the other end of
the serial port is simply not connected.
So whom do you expect to reply?

In a mean time I've debugged more
outstanding problems in that area.
The update for x86_64 will be there
in half an hour.

**Comment by nelgin** [comment]
That output was the result of what went to ttyS21 when running the program.

The user can use telnet, ssh, or rlogin to connect to the BBS. When the door runs, it should communicate with the tcp/ip port the user is on. On the BBS I have it set to use /FD as a command line option, which is supposed to use the fossil driver, which is x00.exe. I have the BBS to use Fossil. Why it's insisting on using the com port, I have no idea.

**Comment by stsp** [comment]
> That output was the result of what went to ttyS21 when running the program.

How is that appeared in dosemu_boot.log?

Fossil also uses com port, or do you mean
your fossil redirects things to tcp/ip?
IIRC x00.exe is a casual fossil driver w/o
any tcp/ip support. Have you tried dosemu's
fossil instead btw?

**Comment by nelgin** [comment]
I have no idea how it appeared in the dosemu_boot.log, sorry. Don't have an answer for that.

I didn't know dosemu had a fossil driver.  I've not had a problem with x00.exe, but it seems Synchronet also provides some sort of fossil driver so maybe that's helping out? I have no idea. 

dosemu and dosemu.bin make no mention of a fossil driver, the docs ... please provide more details and I can give it a try.

**Comment by stsp** [comment]
```
C:\>fossil
dosemu FOSSIL emulator: installed.
```
This is all of the instruction.
Of course this is also a simple fossil,
no tcp/ip redirection or anything like
that. So I still don't quite understand
how do you redirect and who's gonna
answer the ansi requests.

**Comment by stsp** [comment]
We have "vmodem" for tcp/ip, but I
don't think server mode is supported.
IIRC it can only dial-out to telnet server.

**Comment by nelgin** [comment]
Maybe what we need is a $_com1 option that redirects the com port to the users tcp/ip session instead?

**Comment by stsp** [comment]
> Maybe what we need is a $_com1 option that redirects the com port to the users tcp/ip session instead?

We already have 2: "virtual" and comredir.
Did dosemu fossil work?

**Comment by nelgin** [comment]
Maybe we need a third?

No, I've not tried it yet. I'll try it tomorrow but I don't think it's going to help much if, as you say, it's not meant to send communications to the tcp/ip port.

**Comment by nelgin** [comment]
OK, it's all working now I finally have a combination of dosemu.conf, batch file that loads stuff and Synchronet configuration. It's all working as it should.

Thanks again for your help on this. It looks like we may have squished some bugs while we were at it so time not wasted, I hope.

**Comment by stsp** [comment]
> It's all working as it should.

What working? ANSI detection via serial
port? With no one on the other side?

**Comment by nelgin** [comment]
Yup, the game is playable from the BBS without any issues.

**Comment by stsp** [comment]
Hope the quality of your reports
improve the next time you get another
problem. Its never been that difficult
to stay polite.

**Comment by andrewbird** [comment]
> Yup, the game is playable from the BBS without any issues.

Yes, but what did you tweak to make it work?

**Comment by nelgin** [comment]
I have $_com1 = "virtual" in my dosemu.ini and in the BBS I needed to make sure "FOSSIL or UART" was selected. I think I had it set to "Standard".

**Comment by andrewbird** [comment]
And are you using the x00 FOSSIL driver or Dosemu's built in?

**Comment by nelgin** [comment]
I'm using x00.

**Comment by nelgin** [comment]
> Hope the quality of your reports improve the next time you get another problem. Its never been that difficult to stay polite.

I have been nothing but polite and cordial to you despite your jabs at me, and this is yet another one. Where have I been impolite to you, exactly?

**Comment by stsp** [comment]
I didn't say you were impolite.
I said it was difficult for ME to remain
polite, in spite of the quality of an answers.
Fortunately I was able to set up the
testing scenario myself, so was able
to debug independently of whatever you do.
If the ANSI problem was ever fixed, it
wasn't fixed by me, but rather by you,
in your setup. And of course you decided
to hide the way you fixed it, but not that
I care (maybe Andrew does :)

**Comment by nelgin** [comment]
So, Andrew asked and I said so not sure what the problem is. I'll try to unshitty my bug reporting in future.

**Comment by stsp** [comment]
You have never described your architecture,
namely, who replies to ANSI requests via serial
port. Even if that was asked multiple times.
You even managed to provide the garbled log.

> I'll try to unshitty my bug reporting in future.

That will help, thanks.

**Comment by nelgin** [comment]
As I said, the server has no serial port, so there's nothing to respond to. All connections are via tcp/ip so I cannot answer that.

The mangled, garbled log was mangled and garbled because that's what dosemu put into it. I have never manually added anything to the log nor have I ever redirected any output to the log. That's all dosemu's doing so don't blame me for that.

**Comment by stsp** [comment]
> As I said, the server has no serial port, so there's nothing to respond to.
> All connections are via tcp/ip so I cannot answer that.

So you somehow route them via
tcp/ip, and there is some ansi emulator
on the way, and all you can say is "I don't
know"?

> That's all dosemu's doing so don't blame me for that.

Can I reproduce that garbled log?
If so - how?

**Comment by andrewbird** [comment]
I don't know but perhaps when debug is -D9+s the serial port traffic ends up in the log?

**Comment by stsp** [comment]
```
SER0: Async notification received
SER0: Got 4 bytes, 0 in buffer
SER0: Got data byte: 0x61
SER0: Got data byte: 0x61
SER0: Got data byte: 0x61
SER0: Got data byte: 0xa
```
That's how my log shows the traffic.
I've never seen a binary blob within.

**Comment by stsp** [comment]
Ok, indeed in "virtual" mode the tty output
was getting into the log. This is now fixed.
But for me its purely textual.
In the log of this ticket however, we see a
binary blob. It has things like:
`d..o..s..e..m..u..2.. ..2.....0..p..r..e..9..`
etc, but is this some kind of unicode?
3 bytes per symbol?
What can that be?

**Comment by andrewbird** [comment]
No idea then.  @nelgin I presume you copied the log you posted from ~/.dosemu/boot.log rather than copying the output from the terminal window?

**Comment by andrewbird** [comment]
Posts crossed, ignore my last!

**Comment by stsp** [comment]
I believe you can set comments to hidden.

**Comment by stsp** [comment]
Ok, judging from the code, it seems
it was indeed possible to get the garbled
log. :(

**Comment by nelgin** [comment]
I'm not sure. If you can provide more of the decoded binary then I can maybe see where it's coming from. Maybe it's the boot text?

```dosemu2 2.0pre9
Get the latest code cat http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
```
etc etc?


Oh, to address your comment on the bad report and not using the template, this originally started as a discussion and when I realized it was possibly a bug, I used "reference in a new issue". So, yes, I probably should have converted it to the proper template form, however it didn't cross my mind. I didn't just blindly create a crap report, it was because of the reference a new issue. Again, not trying to make your life hard on purpose, a genuine error on my part.

**Comment by stsp** [comment]
The problem is the quality of replies.
We don't know anything about your setup.
All the fixes were done by setting an
independent test-cases, and nothing
related to ANSI, as there is no idea
where in your setup ANSI resides.
Skipping templates and all that, are
just the minor problems. But when
neither of the question I post, gets the
definite answer, that quickly became
a problem.

**Comment by nelgin** [comment]
Since it's running in as a backend of a BBS system, it's not as easy as just running dosemu from the command line. There's stuff I don't know what's going on between the BBS and dosemu. As I mentioned, I used the original dosemu.conf for testing but most, if not all, these programs are not meant to run standalone but via a BBS using fossil drivers and like. It's not as easy as if I'm trying to play Doom or Pacman. Trust me, I wish it was. 

I now understand a lot more about what is going on now than when I first reported this.

Ansi detection. I thought it was talking about the presence of ansi.sys or nansi.sys in my case, then I discovered it was sending the ^[[6n and I didn't know why the terminal wasn't responding. Well, it's because it was going out the com port. Once I redirected com to a tty device it responded so that was a big clue. Then I had to figure out why it wouldn't work in the BBS, which was a duff setting on my part, I guess, not having UART/Fossil selected. Sometimes, I can't give a definite answer so I do my best to answer with what I know. I don't know the inner workings of dosemu not the bbs not how they interact and I don't care to either. I just report what I see, or what I think I see. 

Anyway, this is my last comment on this. Like I said, I appreciate your help. I wish I had your depth of knowledge, but I don't so yes, please be patient as I try and work through what you request.

**Comment by stsp** [comment]
> Once I redirected com to a tty device it responded so that was a big clue.

How have you done that, other than
by using "virtual", which is already such
a redirection?

**Comment by nelgin** [comment]
I opened a shell then did chmod 777 /dev/pts/5, which was the tty device that opened, and then setting $_com1 to /dev/pts/5
Then, when I ran dosemu it sent the output to that pty which responded to the ^[[6n request.

I didn't expect it to work but that's what got me past the ansi detection issue. I thought I mentioned I had done this, but I don't see it. It's maybe in a half-composed post in another tab somewhere.

**Comment by stsp** [comment]
So do you mean its not what
"virtual" does, because it does
essentially the same thing?
If you confirm this doesn't work
with "virtual" but works with
setting the explicit pts name, that
might be a matter for another bug
report.

**Comment by nelgin** [comment]
Haha, yes...I found a rather lengthy post I was going to make and was going to add more details and it was never sent, that was detailing the pts so again, my bad. I thought I had sent but hadn't.

It's working with "virtual" everything is working as it should be. Thank you.

**Comment by stsp** [comment]
So am I right you don't even need nansi driver?
Are you doing something special to switch
terminal into an ANSI mode?

**Comment by nelgin** [comment]
Nothing that I know of. I just connect with putty and that's it when redirecting to the tty.
